# Site settings
title: Riviera Sperduto - Developer Portfolio
email: riviera.t.sperduto13@gmail.com
description: >-
  Portfolio of Riviera Sperduto - Full Stack Developer, Cloud/Solutions Architect, and AI Developer.
  Showcasing projects, skills, and services.
baseurl: ""
url: "https://rivie13.github.io"
github_username: rivie13

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination settings for blog
paginate: 5
paginate_path: "/blog/page:num/"

# Social media links
social_links:
  github: rivie13
  linkedin: # Add your LinkedIn username when available 