endpoints:
  newChat: "https://blogpost-interactive-elements.azurewebsites.net/api/NewMethodProxy?code={{ site.env.NEWMETHOD_CHAT_KEY }}"
  newSnippet: "https://blogpost-interactive-elements.azurewebsites.net/api/NewMethodProxy/tower-snippet?code={{ site.env.NEWMETHOD_SNIPPET_KEY }}"
  oldChat: "https://blogpost-interactive-elements.azurewebsites.net/api/OldMethodProxy?code={{ site.env.OLDMETHOD_CHAT_KEY }}"
  oldSnippet: "https://blogpost-interactive-elements.azurewebsites.net/api/OldMethodProxy/tower-snippet?code={{ site.env.OLDMETHOD_SNIPPET_KEY }}"
  executeTwoSum: "https://blogpost-interactive-elements.azurewebsites.net/api/ExecuteTwoSumSolutionProxy?code={{ site.env.EXECUTETWOSUM_KEY }}" 